<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="15.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageReference Include="Minio" Version="6.0.3" />
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PodMD.Domain\PodMD.Domain.csproj" />
    <ProjectReference Include="..\PodMD.Shared\PodMD.Shared.csproj" />
  </ItemGroup>

</Project>
