<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PodMD.Domain\PodMD.Domain.csproj" />
    <ProjectReference Include="..\PodMD.Shared\PodMD.Shared.csproj" />
  </ItemGroup>

</Project>
